// swift-tools-version: 5.9
import PackageDescription

// This file is auto-generated by the release workflow. Do not edit manually.
let package = Package(
    name: "Talk360SDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "Talk360SDK", targets: ["Talk360SDK"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jitsi/webrtc.git", exact: "124.0.2"),
    ],
    targets: [
        .binaryTarget(
            name: "_Talk360SDK",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev11/_Talk360SDK.xcframework.zip",
            checksum: "f6be1e9b3b1b446b59755be249ef47fff4add5d815ecdd0116e92d1952294dd5"
        ),
        .binaryTarget(
            name: "_Shared",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev11/Shared.xcframework.zip",
            checksum: "aed184b97625cfaea3898cbfa9448dcf4c09a117d2b00633c6d86321d28db601"
        ),
        .target(
            name: "Talk360SDK",
            dependencies: [
                "_Talk360SDK",
                "_Shared",
                .product(name: "WebRTC", package: "webrtc"),
            ],
            path: "Sources/Talk360SDK"
        ),
    ]
)
