// swift-tools-version: 5.9
import PackageDescription

// This file is auto-generated by the release workflow. Do not edit manually.
let package = Package(
    name: "Talk360SDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "Talk360SDK", targets: ["Talk360SDK"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jitsi/webrtc.git", exact: "124.0.2"),
    ],
    targets: [
        .binaryTarget(
            name: "_Talk360SDK",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev10/_Talk360SDK.xcframework.zip",
            checksum: "2dfc8744f45bbfff6acaa48536c7a68fdbdc844727925931ff9759703cd9052d"
        ),
        .binaryTarget(
            name: "_Shared",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev10/Shared.xcframework.zip",
            checksum: "249fa174352631e90a7b426acb69d7914f6f99ceb2cf451b41f99bb9fd759bef"
        ),
        .target(
            name: "Talk360SDK",
            dependencies: [
                "_Talk360SDK",
                "_Shared",
                .product(name: "WebRTC", package: "webrtc"),
            ],
            path: "Sources/Talk360SDK"
        ),
    ]
)
