// swift-tools-version: 5.9
import PackageDescription

// This file is auto-generated by the release workflow. Do not edit manually.
let package = Package(
    name: "Talk360SDK",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "Talk360SDK", targets: ["Talk360SDK"]),
    ],
    dependencies: [
        .package(url: "https://github.com/jitsi/webrtc.git", exact: "124.0.2"),
    ],
    targets: [
        .binaryTarget(
            name: "_Talk360SDK",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev14/_Talk360SDK.xcframework.zip",
            checksum: "25eb6a8bc0d83697a1b051687fce6331f20412d071456e58ac755886f50f3f3d"
        ),
        .binaryTarget(
            name: "_Shared",
            url: "https://github.com/Talk360/talk360-sdk-ios/releases/download/v0.1.0-dev14/Shared.xcframework.zip",
            checksum: "cfb869a6e8038d08e821187ec127d8fe1f1f6ea0a2f73fb595f707e4b80e3041"
        ),
        .target(
            name: "Talk360SDK",
            dependencies: [
                "_Talk360SDK",
                "_Shared",
                .product(name: "WebRTC", package: "webrtc"),
            ],
            path: "Sources/Talk360SDK"
        ),
    ]
)
